/**
 * NearShare macOS Direct Transfer Validation Scenario Matrix
 *
 * Defines 30 comprehensive physical and deterministic scenarios
 * covering the full native MultipeerConnectivity lifecycle.
 */

import type { MacOSDirectScenarioDefinition } from './MacOSDirectValidationTypes';

export const MACOS_DIRECT_SCENARIOS: MacOSDirectScenarioDefinition[] = [
  {
    id: 'scen-direct-001',
    code: 'DIRECT-PHYS-001',
    name: 'Peer Discovery',
    description: 'Verify over-the-air peer discovery between two physical Macs advertising and browsing nearshare-p2p',
    category: 'discovery',
    requiresTransfer: false,
  },
  {
    id: 'scen-direct-002',
    code: 'DIRECT-PHYS-002',
    name: 'Peer Invitation',
    description: 'Verify invitation transmission and acceptance via native MCNearbyServiceAdvertiser / MCNearbyServiceBrowser',
    category: 'pairing',
    requiresTransfer: false,
  },
  {
    id: 'scen-direct-003',
    code: 'DIRECT-PHYS-003',
    name: 'Pairing & Trust Handshake',
    description: 'Execute NearShare cryptographic handshake and mutual authentication across native transport',
    category: 'pairing',
    requiresTransfer: false,
  },
  {
    id: 'scen-direct-004',
    code: 'DIRECT-PHYS-004',
    name: 'Secure Session Establishment',
    description: 'Establish ephemeral ECDH key agreement and instantiate SecureTransportSession channel',
    category: 'session',
    requiresTransfer: false,
  },
  {
    id: 'scen-direct-005',
    code: 'DIRECT-PHYS-005',
    name: '0-Byte Boundary File Transfer',
    description: 'Validate zero-byte empty file offer, stream framing, and atomic creation on receiver',
    category: 'transfer',
    requiresTransfer: true,
    payloadSize: 0,
  },
  {
    id: 'scen-direct-006',
    code: 'DIRECT-PHYS-006',
    name: '1-Byte Boundary File Transfer',
    description: 'Validate single-byte transfer through native NSOutputStream/NSInputStream boundary',
    category: 'transfer',
    requiresTransfer: true,
    payloadSize: 1,
  },
  {
    id: 'scen-direct-007',
    code: 'DIRECT-PHYS-007',
    name: '4 KiB Small Block Transfer',
    description: 'Verify 4 KiB block transfer matching standard filesystem cluster boundary',
    category: 'transfer',
    requiresTransfer: true,
    payloadSize: 4 * 1024,
  },
  {
    id: 'scen-direct-008',
    code: 'DIRECT-PHYS-008',
    name: '1 MiB Standard Stream Transfer',
    description: 'Verify 1 MiB chunked payload through secure frame encoding and native stream',
    category: 'transfer',
    requiresTransfer: true,
    payloadSize: 1024 * 1024,
  },
  {
    id: 'scen-direct-009',
    code: 'DIRECT-PHYS-009',
    name: '100 MiB High-Throughput Transfer',
    description: 'Verify multi-chunk 100 MiB transfer with backpressure controller and flow control',
    category: 'transfer',
    requiresTransfer: true,
    payloadSize: 100 * 1024 * 1024,
  },
  {
    id: 'scen-direct-010',
    code: 'DIRECT-PHYS-010',
    name: 'Large File (500 MiB / 1 GiB) Transfer',
    description: 'Verify stress payload transmission with bounded memory and disk space verification',
    category: 'transfer',
    requiresTransfer: true,
    payloadSize: 500 * 1024 * 1024,
  },
  {
    id: 'scen-direct-011',
    code: 'DIRECT-PHYS-011',
    name: 'Nested Folder Manifest Transfer',
    description: 'Transfer complex folder hierarchy, preserving relative paths and sanitized directory boundaries',
    category: 'transfer',
    requiresTransfer: true,
  },
  {
    id: 'scen-direct-012',
    code: 'DIRECT-PHYS-012',
    name: 'Unicode Filename Transfer',
    description: 'Verify UTF-8 multibyte normalization (e.g. Japanese, Arabic, Emojis) across wire protocol',
    category: 'transfer',
    requiresTransfer: true,
    payloadSize: 64 * 1024,
  },
  {
    id: 'scen-direct-013',
    code: 'DIRECT-PHYS-013',
    name: 'Compressed Archive (.zip/.tar.gz) Transfer',
    description: 'Verify binary compression integrity without premature de-encapsulation',
    category: 'transfer',
    requiresTransfer: true,
    payloadSize: 10 * 1024 * 1024,
  },
  {
    id: 'scen-direct-014',
    code: 'DIRECT-PHYS-014',
    name: 'Arbitrary Binary (.apk/.iso) Transfer',
    description: 'Transfer opaque binary payload verifying strict byte-exact receiver reproduction',
    category: 'transfer',
    requiresTransfer: true,
    payloadSize: 15 * 1024 * 1024,
  },
  {
    id: 'scen-direct-015',
    code: 'DIRECT-PHYS-015',
    name: 'Pause In-Flight Transfer',
    description: 'Pause transfer mid-stream and confirm producer halts while native connection remains open',
    category: 'control',
    requiresTransfer: true,
  },
  {
    id: 'scen-direct-016',
    code: 'DIRECT-PHYS-016',
    name: 'Resume Paused Transfer',
    description: 'Resume paused transfer and confirm transmission continues from checkpoint without byte 0 restart',
    category: 'control',
    requiresTransfer: true,
  },
  {
    id: 'scen-direct-017',
    code: 'DIRECT-PHYS-017',
    name: 'Transfer Cancellation Cleanup',
    description: 'Cancel transfer and verify stream closes, memory permits drain, and terminal history writes',
    category: 'control',
    requiresTransfer: true,
  },
  {
    id: 'scen-direct-018',
    code: 'DIRECT-PHYS-018',
    name: 'Disconnect Mid-Transfer',
    description: 'Simulate abrupt physical radio loss and confirm state enters recoverable interruption',
    category: 'recovery',
    requiresTransfer: true,
  },
  {
    id: 'scen-direct-019',
    code: 'DIRECT-PHYS-019',
    name: 'Transport Reconnection',
    description: 'Re-establish native Multipeer stream and obtain new ephemeral connectionId',
    category: 'recovery',
    requiresTransfer: false,
  },
  {
    id: 'scen-direct-020',
    code: 'DIRECT-PHYS-020',
    name: 'Resume After Reconnect',
    description: 'Perform receiver-authoritative range negotiation and resume transfer to full completion',
    category: 'recovery',
    requiresTransfer: true,
  },
  {
    id: 'scen-direct-021',
    code: 'DIRECT-PHYS-021',
    name: 'Bidirectional SHA-256 Integrity Verification',
    description: 'Validate cryptographic SHA-256 hash matching between sender file and receiver disk write',
    category: 'integrity',
    requiresTransfer: true,
    payloadSize: 5 * 1024 * 1024,
  },
  {
    id: 'scen-direct-022',
    code: 'DIRECT-PHYS-022',
    name: 'Single History Record Logging',
    description: 'Confirm completed or cancelled session emits exactly one non-duplicate history entry',
    category: 'lifecycle',
    requiresTransfer: true,
  },
  {
    id: 'scen-direct-023',
    code: 'DIRECT-PHYS-023',
    name: 'Blocked Peer Rejection',
    description: 'Reject invitations and frame processing from blocked peer identifiers',
    category: 'security',
    requiresTransfer: false,
  },
  {
    id: 'scen-direct-024',
    code: 'DIRECT-PHYS-024',
    name: 'Revoked Session Key Invalidation',
    description: 'Verify session revocation zeroizes keys and immediately rejects subsequent ciphertext frames',
    category: 'security',
    requiresTransfer: false,
  },
  {
    id: 'scen-direct-025',
    code: 'DIRECT-PHYS-025',
    name: 'Expired / Mismatched Session ID Frame Drop',
    description: 'Silently drop frames containing mismatched or expired session IDs',
    category: 'security',
    requiresTransfer: false,
  },
  {
    id: 'scen-direct-026',
    code: 'DIRECT-PHYS-026',
    name: 'Duplicate Frame / Replay Protection',
    description: 'Flag and drop duplicate sequence frames without disrupting in-order stream pipeline',
    category: 'security',
    requiresTransfer: false,
  },
  {
    id: 'scen-direct-027',
    code: 'DIRECT-PHYS-027',
    name: 'Corrupted Ciphertext AEAD Failure',
    description: 'Verify modified ciphertext bytes fail AES-GCM tag check and trigger fail-closed termination',
    category: 'security',
    requiresTransfer: false,
  },
  {
    id: 'scen-direct-028',
    code: 'DIRECT-PHYS-028',
    name: 'Peer Device Disappearance',
    description: 'Handle unexpected peer departure with clean resource invalidation and no memory leak',
    category: 'lifecycle',
    requiresTransfer: false,
  },
  {
    id: 'scen-direct-029',
    code: 'DIRECT-PHYS-029',
    name: 'App Background / Tray Continuity',
    description: 'Confirm active Direct streams persist during window hide/tray minimize while process is alive',
    category: 'lifecycle',
    requiresTransfer: true,
  },
  {
    id: 'scen-direct-030',
    code: 'DIRECT-PHYS-030',
    name: 'Clean App Shutdown Flushes Checkpoints',
    description: 'Confirm application quit flushes active transfer checkpoints and disconnects Multipeer session',
    category: 'lifecycle',
    requiresTransfer: false,
  },
];
